GUI_TEMPLATE = """
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("{{ assets_path }}")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class Tkd(Tk):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self.geometry("{{ window.width }}x{{ window.height }}")
        self.configure(bg = "{{ window.bg_color }}")

        self.canvas = Canvas(
            self,
            bg = "{{ window.bg_color }}",
            height = {{ window.height }},
            width = {{ window.width }},
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)


        {%- for element in elements -%}
            {{ element.to_code() }}
        {%- endfor -%}
# need this or next line has indent removed for some reason!
        self.resizable(False, False)

"""

APP_TEMPLATE = """
#
from gui import Tkd


{% for button in range(1,buttonCount+1) -%}
def button_click_{{ button }}():
    print("CLICK BUTTON {{ button }}")


{% endfor -%}
command_list = [
    None,
    {% for button in range(1,buttonCount+1) -%}
    button_click_{{ button }},
    {% endfor -%}
]


def main():
    window = Tkd(*command_list)
    window.mainloop()


if __name__ == "__main__":
    main()

"""
